apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: mysql:5.6
            env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root_password
            - name: BACKUP_PATH
              value: "/backup"
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            emptyDir: {}